[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[project]
name = "slyme"
dynamic = ["version"]
description = "Slyme is a highly composable functional execution framework."
readme = "README.md"
authors = [{ name = "The SlymeLab Team" }]
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "typing-extensions>=4.0.0",
]

[project.scripts]
slyme = "slyme.__main__:main"

[project.urls]
Homepage = "https://github.com/slymelab/slyme"

[tool.hatch.build.targets.wheel]
packages = ["src/slyme"]

[tool.ruff.lint.per-file-ignores]
"src/**/*.py" = ["E402", "E741"]
