[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slyme"
version = "0.1.0"
description = "Slyme is a highly composable functional execution framework."
readme = "README.md"
authors = [{ name = "The SlymeLab Team" }]
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "typing-extensions>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/slymelab/slyme"

[tool.hatch.build.targets.wheel]
packages = ["src/slyme"]

[tool.ruff.lint.per-file-ignores]
"src/**/*.py" = ["E402", "E741"]
